import type { LlmMessage } from "@/services/anna/llm";

// ---------------------------------------------------------------------------
// Daily Delight — one fresh small joy per day, generated by the LLM.
// Cached per calendar day so it costs exactly one LLM call a day.
// ---------------------------------------------------------------------------

export type DelightKind = "moment" | "quote";

export interface DailyDelight {
  text: string;
  kind: DelightKind;
  /** YYYY-MM-DD the delight was generated for. */
  date: string;
  /** True when this came from the local fallback pool (LLM unavailable). */
  fallback: boolean;
}

const SYSTEM = `You are Money Buddy, a warm friend who notices life's small joys.
Write one short daily delight for the user.

Pick ONE of these two forms:
- A tiny everyday moment worth noticing (morning light, a good stretch, the smell of fresh bread, a stranger holding the door). Concrete and sensory.
- A short original quote about savoring life or being kind to yourself. Never a famous quote, never preachy.

Rules:
- 1–2 sentences, under 35 words, simple everyday English.
- Warm and gentle. Never mention money, budgets, spending, or finances.
- Never give advice or instructions. Just offer the moment.
- Respond with ONLY the delight text — no quotes around it, no preamble.`;

export function buildDelightMessages(recentTexts: string[]): LlmMessage[] {
  const avoid =
    recentTexts.length > 0
      ? `\nMake it different from these recent ones:\n${recentTexts
          .slice(-5)
          .map((t) => `- ${t}`)
          .join("\n")}`
      : "";
  return [
    { role: "system", content: SYSTEM },
    { role: "user", content: `Write today's delight.${avoid}` },
  ];
}

/** Local fallback pool — used when the LLM is unavailable. Picked by day-of-year. */
export const FALLBACK_DELIGHTS: string[] = [
  "The first sip of a warm drink on a cold morning is a small kind of magic.",
  "Sunlight through leaves makes patterns nothing designed on purpose.",
  "A good stretch after sitting too long feels like a reset button.",
  "Someone held the door today. Small kindnesses travel farther than we know.",
  "Fresh bread smells like someone, somewhere, is having a good day.",
  "The sky does a new painting every evening and never asks for applause.",
  "A deep breath in the middle of a busy day is a gift you give yourself.",
  "Warm socks on a cold floor. That's it. That's the delight.",
  "Birdsong in the morning doesn't care about your to-do list.",
  "The perfect bite — when everything on the plate comes together at once.",
  "Rain on the window while you're cozy inside is nature's lullaby.",
  "A genuine smile from a stranger can quietly reroute your whole day.",
  "The smell of rain on dry pavement has a name: petrichor. Now you know.",
  "Finishing something small still counts. Celebrate the tiny wins.",
];

export function fallbackDelight(dateKey: string): DailyDelight {
  const [y, m, d] = dateKey.split("-").map(Number);
  const dayOfYear = Math.floor(
    (Date.UTC(y, m - 1, d) - Date.UTC(y, 0, 0)) / 86_400_000
  );
  return {
    text: FALLBACK_DELIGHTS[dayOfYear % FALLBACK_DELIGHTS.length],
    kind: "moment",
    date: dateKey,
    fallback: true,
  };
}

/** Clean an LLM response into a one-line delight. */
export function cleanDelightText(raw: string): string {
  return raw
    .split("\n")[0]
    .replace(/^["'“”\s]+|["'“”\s]+$/g, "")
    .trim()
    .slice(0, 200);
}
