import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { Expense, MonthlyBudget } from "@/lib/types";
import { categoryLabel } from "@/lib/categories";
import { totalsByCategory, sumExpenses } from "@/lib/analytics";
import { money } from "@/lib/utils";
import { THEME_BACKGROUNDS } from "@/services/theme/themeBackgrounds";
import type { ThemeId } from "@/services/theme/themes";

export interface StatementOptions {
  expenses: Expense[];
  budgets: MonthlyBudget[];
  /** e.g. "2026-10" */
  monthKey: string;
  monthLabel: string;
  currency: string;
  theme: ThemeId;
}

const PAGE_W = 210; // A4 mm
const PAGE_H = 297;
const MARGIN = 14;

/** Draw the theme background full-bleed, then a translucent white panel for content. */
function paintBackground(doc: jsPDF, theme: ThemeId): void {
  const bg = THEME_BACKGROUNDS[theme];
  try {
    doc.addImage(bg, "JPEG", 0, 0, PAGE_W, PAGE_H);
  } catch {
    /* background is decorative — skip on failure */
  }
  // Translucent content panel for readability
  doc.setFillColor(255, 255, 255);
  // jsPDF has no alpha for rect fill in all versions; use light solid panel
  doc.setGState(doc.GState({ opacity: 0.88 }));
  doc.rect(MARGIN - 4, MARGIN - 4, PAGE_W - 2 * (MARGIN - 4), PAGE_H - 2 * (MARGIN - 4), "F");
  doc.setGState(doc.GState({ opacity: 1 }));
}

function header(doc: jsPDF, opts: StatementOptions): number {
  let y = MARGIN + 6;
  // App logo — styled wordmark
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text("Money Companion", MARGIN, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  y += 7;
  doc.text(`Monthly Statement — ${opts.monthLabel}`, MARGIN, y);
  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  return y + 8;
}

function summary(doc: jsPDF, opts: StatementOptions, y: number): number {
  const total = sumExpenses(opts.expenses);
  const byCat = totalsByCategory(opts.expenses);
  const overallBudget = opts.budgets.find((b) => b.categoryId === null);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(40, 40, 40);
  doc.text("Summary", MARGIN, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Total spent: ${money(total, opts.currency)}`, MARGIN, y);
  y += 6;
  doc.text(`Transactions: ${opts.expenses.length}`, MARGIN, y);
  y += 6;
  if (overallBudget) {
    doc.text(`Budget: ${money(overallBudget.amount, overallBudget.currency)}`, MARGIN, y);
    y += 6;
  }
  if (byCat.length > 0) {
    y += 2;
    doc.setFont("helvetica", "bold");
    doc.text("By category", MARGIN, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    for (const c of byCat.slice(0, 8)) {
      doc.text(`${categoryLabel(c.categoryId)}: ${money(c.total, opts.currency)}`, MARGIN + 4, y);
      y += 5.5;
    }
  }
  return y + 6;
}

function transactionsTable(doc: jsPDF, opts: StatementOptions, startY: number): void {
  const rows = [...opts.expenses]
    .sort((a, b) => a.date.localeCompare(b.date))
    .map((e) => [
      e.date,
      e.description || categoryLabel(e.categoryId),
      categoryLabel(e.categoryId),
      money(e.amount, e.currency),
    ]);

  // didDrawPage fires for the first table page too — skip it since we
  // already painted + drew header/summary there.
  let firstPageSkipped = false;
  autoTable(doc, {
    startY,
    head: [["Date", "Description", "Category", "Amount"]],
    body: rows,
    margin: { left: MARGIN, right: MARGIN },
    styles: { fontSize: 9, cellPadding: 2.5 },
    headStyles: { fillColor: [74, 52, 40], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 242, 238] },
    didDrawPage: () => {
      if (!firstPageSkipped) {
        firstPageSkipped = true;
        return;
      }
      paintBackground(doc, opts.theme);
    },
  });
}

export function exportMonthlyStatement(opts: StatementOptions): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  paintBackground(doc, opts.theme);
  let y = header(doc, opts);
  y = summary(doc, opts, y);
  transactionsTable(doc, opts, y);

  // Footer on last page
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(130, 130, 130);
    doc.text(
      `Generated by Money Companion on ${new Date().toISOString().slice(0, 10)} — Page ${i} of ${pages}`,
      MARGIN,
      PAGE_H - 8
    );
  }

  doc.save(`money-companion-statement-${opts.monthKey}.pdf`);
}
